const svg=document.querySelector("#graph"),viewport=document.querySelector("#viewport"),edgesG=document.querySelector("#edges"),nodesG=document.querySelector("#nodes"),erasG=document.querySelector("#eras"),fogG=document.querySelector("#fog"),detail=document.querySelector("#detail"),search=document.querySelector("#search"),domain=document.querySelector("#domain"),status=document.querySelector("#status"),frontierOnly=document.querySelector("#frontierOnly"),stats=document.querySelector("#stats"),shell=document.querySelector("#mapShell");
const STATUS={foundational:["Foundational","#ffbf57"],established:["Strongly established","#65f5b0"],active:["Active field","#66bfff"],disputed:["Disputed","#ffc857"],frontier:["Frontier / unresolved","#c497ff"],invalidated:["Invalidated / falsified","#ff4d67"],historical:["Historical / superseded","#8e96a8"],"dependency-broken":["Broken dependency","#ff4d67"],"review-required":["Review required","#ffc857"]};
const NS="http://www.w3.org/2000/svg";const mk=(n,a={})=>{const x=document.createElementNS(NS,n);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));return x};
let model,nodeById=new Map(),pos=new Map(),view={scale:1,x:0,y:0,drag:false,sx:0,sy:0,px:0,py:0};

async function boot(){
 const r=await fetch("./data/knowledge.json");model=await r.json();await addOlogies();nodeById=new Map(model.nodes.map(n=>[n.id,n]));derive();controls();layout();draw();bind();
}
async function addOlogies(){
 const t=await (await fetch("./data/ologies.tsv")).text();
 const parent={earth:"field.geology",life:"field.biology",health:"practice.medicine",social:"field.sociology",humanities:"field.philosophy",physical:"field.physics",information:"field.cognitive-science",engineering:"field.engineering",formal:"field.logic"};
 const existing=new Map(model.nodes.map(n=>[n.label.toLowerCase(),n]));
 for(const line of t.split(/\r?\n/).slice(1)){if(!line.trim())continue;const [label,d,e]=line.split("\t");const old=existing.get(label.toLowerCase());if(old){if(label.toLowerCase().endsWith("ology")&&!old.tags?.includes("ology"))(old.tags??=[]).push("ology");continue}const slug=label.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),id="ology."+slug,n={id,label,kind:"field",domain:d,era:e,status:"active",summary:"Curated seed entry in the expandable -ology registry: "+label+".",tags:["ology","registry-seed"],sources:[],frontier:false,aliases:[]};model.nodes.push(n);existing.set(label.toLowerCase(),n);if(parent[d])model.edges.push({source:parent[d],target:id,type:"derived_from",dependency:"soft"})}
}
function derive(){
 model.nodes.forEach(n=>n._status=n.status);const hard=new Map(),soft=new Map();for(const e of model.edges){if(!["depends_on","enabled","derived_from"].includes(e.type))continue;const m=e.dependency==="hard"?hard:soft;if(!m.has(e.source))m.set(e.source,[]);m.get(e.source).push(e.target)}
 const invalid=model.nodes.filter(n=>n.status==="invalidated").map(n=>n.id),broken=new Set(),q=[...invalid];while(q.length){const id=q.shift();for(const c of hard.get(id)||[]){if(!broken.has(c)&&!invalid.includes(c)){broken.add(c);q.push(c)}}}
 broken.forEach(id=>{const n=nodeById.get(id)||model.nodes.find(x=>x.id===id);if(n&&n.status!=="invalidated")n._status="dependency-broken"});
 const review=new Set(),q2=[...invalid,...broken];while(q2.length){const id=q2.shift();for(const c of soft.get(id)||[]){if(!review.has(c)){review.add(c);q2.push(c)}}}
 review.forEach(id=>{const n=model.nodes.find(x=>x.id===id);if(n&&!["invalidated","dependency-broken"].includes(n._status))n._status="review-required"});
}
function controls(){
 model.domains.forEach(d=>domain.add(new Option(d.label,d.id)));Object.entries(STATUS).forEach(([k,v])=>status.add(new Option(v[0],k)));
 const box=document.querySelector("#legend");["foundational","established","active","frontier","invalidated","dependency-broken","review-required","historical"].forEach(k=>{const [label,color]=STATUS[k],r=document.createElement("div");r.className="legendRow";r.innerHTML='<i class="dot" style="background:'+color+';color:'+color+'"></i>'+label;box.append(r)});
}
function layout(){
 const eras=new Map(model.eras.map((e,i)=>[e.id,i])),domains=new Map(model.domains.map((d,i)=>[d.id,i])),groups=new Map();
 model.nodes.forEach(n=>{const k=n.era+"|"+n.domain;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(n)});
 for(const [k,list] of groups){const [e,d]=k.split("|"),ei=eras.get(e)||0,di=domains.get(d)||0;list.sort((a,b)=>a.label.localeCompare(b.label));const cols=Math.max(1,Math.ceil(list.length/5));list.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols);pos.set(n.id,{x:120+ei*285+(col-(cols-1)/2)*42,y:78+di*116+(row-2)*22})})}
}
function draw(){drawEras();drawEdges();drawNodes();drawFog();filter();transform()}
function drawEras(){erasG.replaceChildren();model.eras.forEach((e,i)=>{const x=25+i*285;erasG.append(mk("rect",{x,y:18,width:260,height:1170,rx:18,class:"eraBand"}));const t=mk("text",{x:x+12,y:42,class:"eraLabel"});t.textContent=e.label;erasG.append(t)})}
function curve(a,b){const dx=Math.max(45,(b.x-a.x)*.48);return "M "+a.x+" "+a.y+" C "+(a.x+dx)+" "+a.y+", "+(b.x-dx)+" "+b.y+", "+b.x+" "+b.y}
function drawEdges(){edgesG.replaceChildren();model.edges.forEach(e=>{const a=pos.get(e.source),b=pos.get(e.target);if(!a||!b)return;edgesG.append(mk("path",{d:curve(a,b),class:"edge "+e.type,"data-s":e.source,"data-t":e.target}))})}
function radius(n){return n.kind==="origin"?10:n.kind==="question"?8:n.tags?.includes("ology")?5.4:6.5}
function drawNodes(){nodesG.replaceChildren();for(const n of model.nodes){const p=pos.get(n.id);if(!p)continue;const [_,color]=STATUS[n._status]||STATUS.active,r=radius(n),g=mk("g",{transform:"translate("+p.x+" "+p.y+")",class:"node "+(n.frontier?"frontier ":"")+(n._status==="invalidated"?"invalidated ":"")+(n._status==="dependency-broken"?"broken ":"")+(n._status==="review-required"?"review ":""),"data-id":n.id});g.append(mk("circle",{r:r+7,fill:color,opacity:.05}));g.append(mk("circle",{class:"ring",r:r+5}));g.append(mk("circle",{class:"core",r,fill:color,opacity:.94}));if(n._status==="invalidated")g.append(mk("line",{class:"strike",x1:-r-8,y1:r+4,x2:r+8,y2:-r-4}));const tx=mk("text",{x:r+7,y:3});tx.textContent=n.label;g.append(tx);if(n.tags?.includes("ology")){const s=mk("text",{x:r+7,y:13,class:"sub"});s.textContent="-ology";g.append(s)}g.addEventListener("click",ev=>{ev.stopPropagation();select(n.id)});nodesG.append(g)}}
function drawFog(){const x=25+(model.eras.length-1)*285;fogG.replaceChildren(mk("path",{class:"fog",d:"M "+(x+115)+" 0 C "+(x+35)+" 210 "+(x+180)+" 410 "+(x+70)+" 650 C "+(x+5)+" 820 "+(x+190)+" 1030 "+(x+80)+" 1250 L 2200 1250 L 2200 0 Z"}),mk("path",{class:"fogEdge",d:"M "+(x+100)+" 20 C "+(x+5)+" 260 "+(x+205)+" 470 "+(x+65)+" 710 C "+(x+5)+" 900 "+(x+200)+" 1090 "+(x+95)+" 1230"}))}
function match(n){const q=search.value.trim().toLowerCase();if(domain.value!=="all"&&n.domain!==domain.value)return false;if(status.value!=="all"&&n._status!==status.value)return false;if(frontierOnly.checked&&!n.frontier)return false;if(q&&!([n.label,n.summary,n.kind,...(n.tags||[]),...(n.aliases||[])].join(" ").toLowerCase().includes(q)))return false;return true}
function filter(){const visible=new Set(model.nodes.filter(match).map(n=>n.id));nodesG.querySelectorAll(".node").forEach(g=>g.classList.toggle("muted",!visible.has(g.dataset.id)));edgesG.querySelectorAll(".edge").forEach(p=>p.classList.toggle("muted",!(visible.has(p.dataset.s)&&visible.has(p.dataset.t))));const f=model.nodes.filter(n=>visible.has(n.id)&&n.frontier).length,b=model.nodes.filter(n=>visible.has(n.id)&&["invalidated","dependency-broken","review-required"].includes(n._status)).length;stats.textContent=visible.size+" nodes · "+model.edges.length+" links · "+f+" frontier · "+b+" challenged"}
function downstream(id){const seen=new Set(),q=[id];while(q.length){const x=q.shift();for(const e of model.edges){if(e.source!==x||e.dependency!=="hard"||!["depends_on","enabled","derived_from"].includes(e.type))continue;if(!seen.has(e.target)){seen.add(e.target);q.push(e.target)}}}seen.delete(id);return [...seen]}
function esc(s=""){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function select(id){nodesG.querySelectorAll(".node").forEach(g=>g.classList.toggle("focused",g.dataset.id===id));edgesG.querySelectorAll(".edge").forEach(p=>p.classList.toggle("hot",p.dataset.s===id||p.dataset.t===id));const n=nodeById.get(id),[label,color]=STATUS[n._status]||STATUS.active,inc=model.edges.filter(e=>e.target===id).map(e=>({e,n:nodeById.get(e.source)})).filter(x=>x.n),out=model.edges.filter(e=>e.source===id).map(e=>({e,n:nodeById.get(e.target)})).filter(x=>x.n),impact=downstream(id),reviews=(model.reviews||[]).filter(r=>r.target===id),sources=(n.sources||[]);detail.innerHTML='<div class="kind">'+esc(n.kind)+' · '+esc(model.domains.find(d=>d.id===n.domain)?.label||n.domain)+'</div><h2>'+esc(n.label)+'</h2><span class="badge"><i style="background:'+color+'"></i>'+esc(label)+'</span>'+(n.frontier?'<span class="badge">fog boundary</span>':'')+'<p>'+esc(n.summary||"")+'</p><section><h3>Provenance</h3><ul>'+(sources.length?sources.map(s=>'<li><a href="'+esc(s.url)+'" target="_blank" rel="noreferrer">'+esc(s.title||s.id)+'</a></li>').join(""):"<li>No source attached yet.</li>")+'</ul></section><section><h3>Inherited from</h3><ul>'+(inc.length?inc.map(x=>'<li>'+esc(x.n.label)+' <small>('+esc(x.e.type)+(x.e.dependency?", "+esc(x.e.dependency):"")+')</small></li>').join(""):"<li>Root / no mapped prerequisite.</li>")+'</ul></section><section><h3>Leads to</h3><ul>'+(out.length?out.slice(0,25).map(x=>'<li>'+esc(x.n.label)+' <small>('+esc(x.e.type)+')</small></li>').join(""):"<li>No mapped descendants yet.</li>")+'</ul></section><section><h3>If this node fails</h3><p class="impact">'+(impact.length?impact.length+" mapped hard-dependent node"+(impact.length===1?"":"s")+" require automatic dependency invalidation/review.":"No hard-dependent descendants are currently mapped.")+'</p></section><section><h3>Peer review record</h3>'+(reviews.length?reviews.map(r=>'<div class="reviewCard"><b>'+esc(r.kind)+" · "+esc(r.result)+'</b><p>'+esc(r.summary)+'</p></div>').join(""):"<p>No graph-native reviews yet.</p>")+'</section><section><h3>Node ID</h3><code>'+esc(n.id)+'</code></section>'}
function transform(){viewport.setAttribute("transform","translate("+view.x+" "+view.y+") scale("+view.scale+")")}
function bind(){[search,frontierOnly].forEach(x=>x.addEventListener("input",filter));[domain,status].forEach(x=>x.addEventListener("change",filter));document.querySelector("#reset").onclick=()=>{view={...view,scale:1,x:0,y:0};transform()};svg.addEventListener("wheel",e=>{e.preventDefault();view.scale=Math.max(.35,Math.min(3.5,view.scale*(e.deltaY>0?.9:1.1)));transform()},{passive:false});svg.addEventListener("pointerdown",e=>{if(e.target.closest(".node"))return;view.drag=true;view.sx=e.clientX;view.sy=e.clientY;view.px=view.x;view.py=view.y;shell.classList.add("drag");svg.setPointerCapture(e.pointerId)});svg.addEventListener("pointermove",e=>{if(!view.drag)return;view.x=view.px+e.clientX-view.sx;view.y=view.py+e.clientY-view.sy;transform()});svg.addEventListener("pointerup",()=>{view.drag=false;shell.classList.remove("drag")})}
boot().catch(e=>{console.error(e);detail.innerHTML="<h2>Map failed to load</h2><p>"+esc(e.message)+"</p>"});
