const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const qa=process.env.NEMESIS_QA_NODE_MODULES||path.resolve(__dirname,'../../../release-v17-transport/qa/node_modules');
const {JSDOM}=require(path.join(qa,'jsdom'));
const source=fs.readFileSync(path.join(__dirname,'../contentScript.js'),'utf8');
const start=source.indexOf('  function nbShortNoticeText('),end=source.indexOf('  async function nbRepairFormat(',start);
assert(start>0&&end>start);
const dom=new JSDOM('<main><div id="old"><aside role="alert">The message you submitted was too long</aside></div><div id="owned">[NEMESIS_REQUEST exact-job] quoted: the message you submitted was too long</div><aside role="alert" id="new">The message you submitted was too long, please edit it and resubmit.Retry</aside></main>');
const root=dom.window.document.getElementById('owned');let latest={root};
const ctx={document:dom.window.document,Node:dom.window.Node,elementVisible:()=>true,latestMessage:()=>latest,norm:s=>String(s).replace(/\s+/g,' ').trim()};
vm.createContext(ctx);vm.runInContext(source.slice(start,end)+'globalThis.check=nbRequestRejection;',ctx);
assert.match(ctx.check({root}),/rejected.*too long/);
dom.window.document.getElementById('new').remove();assert.equal(ctx.check({root}),null,'an old alert or words in the owned prompt must not reject the current request');
const alert=dom.window.document.createElement('aside');alert.setAttribute('role','alert');alert.textContent="You've reached the current usage limit";root.after(alert);assert.match(ctx.check({root}),/usage limit/);
for(const phrase of ['Something seems to have gone wrong','Error while generating a response','Error in message stream']){alert.textContent=phrase;assert.match(ctx.check({root}),/platform generation error/);}const quote=dom.window.document.createElement('pre');const nested=alert.cloneNode(true);quote.append(nested);alert.remove();root.after(quote);assert.equal(ctx.check({root}),null,'quoted source text is not a platform error');quote.remove();root.after(alert);
latest={root:alert};assert.equal(ctx.check({root}),null,'an intervening user turn must not attribute its alert to an older job');
latest={root};alert.remove();
const stream=dom.window.document.createElement('section');stream.innerHTML='<div>Error in message stream</div><button>Retry</button>';root.after(stream);
assert.match(ctx.check({root}),/error in message stream/,'actual label plus Retry is detected without assuming an alert role');
const streamQuote=dom.window.document.createElement('pre');stream.replaceWith(streamQuote);streamQuote.append(stream);
assert.equal(ctx.check({root}),null,'even an exact quoted error/Retry pair cannot refresh');
dom.window.close();console.log('PASS current-turn oversized/quota rejection, old-alert/source-text exclusion and intervening-turn attribution. Offline observed-UI regression.');
