/* generated by export_scene.py */
#ifndef SCENE_VALS_H
#define SCENE_VALS_H

#define N_BARS4 4
#define N_BARS3 3
#define BAR_B 0.600000f
#define OBJ_SPAN 3.900000f
#define NUB_SCALE 0.300000f
static const float BAR0_C[4] = { 0.140210773f, -0.434789227f, 0.290210773f, 0.000000000f };
static const int BAR0_NG = 3;
static const float BAR0_G0[4] = { 1.551677467f, 0.251677467f, 0.251677467f, 0.000000000f };
static const float BAR0_G1[4] = { 0.000000000f, 0.300000000f, 0.000000000f, 0.000000000f };
static const float BAR0_G2[4] = { 0.000000000f, 0.000000000f, 0.300000000f, 0.000000000f };
static const float BAR1_C[4] = { 0.575000000f, 0.000000000f, -0.575000000f, 0.000000000f };
static const int BAR1_NG = 3;
static const float BAR1_G0[4] = { 0.253133360f, 1.553133360f, 0.253133360f, 0.000000000f };
static const float BAR1_G1[4] = { 0.300000000f, 0.000000000f, 0.000000000f, 0.000000000f };
static const float BAR1_G2[4] = { 0.000000000f, 0.000000000f, 0.300000000f, 0.000000000f };
static const float BAR2_C[4] = { -0.290210773f, 0.434789227f, -0.140210773f, 0.000000000f };
static const int BAR2_NG = 3;
static const float BAR2_G0[4] = { 0.251677467f, 0.251677467f, 1.551677467f, 0.000000000f };
static const float BAR2_G1[4] = { 0.300000000f, 0.000000000f, 0.000000000f, 0.000000000f };
static const float BAR2_G2[4] = { 0.000000000f, 0.300000000f, 0.000000000f, 0.000000000f };
static const float BAR3_C[4] = { 0.140210773f, -0.434789227f, 0.290210773f, 0.000000000f };
static const int BAR3_NG = 4;
static const float BAR3_G0[4] = { 0.465503240f, 0.075503240f, 0.075503240f, 0.000000000f };
static const float BAR3_G1[4] = { 0.000000000f, 0.090000000f, 0.000000000f, 0.000000000f };
static const float BAR3_G2[4] = { 0.000000000f, 0.000000000f, 0.090000000f, 0.000000000f };
static const float BAR3_G3[4] = { 0.000000000f, 0.000000000f, 0.000000000f, 2.600000000f };
static const float MAGIC3[3] = { 0.577350269f, 0.577350269f, 0.577350269f };
static const float E1_V[3] = { 0.707106781f, 0.000000000f, -0.707106781f };
static const float E2_V[3] = { -0.408248290f, 0.816496581f, -0.408248290f };
static const float OBJ_MIN[3] = { -1.411466693f, -1.553133360f, -1.691888240f };
static const float OBJ_MAX[3] = { 1.691888240f, 1.553133360f, 1.411466693f };
static const float OBJ_CENTER[3] = { 0.141666667f, 0.000000000f, -0.141666667f };
#endif